package ub.cse.algo;

import java.util.*;

public class Solution {

    private Spectrum spectrum;

    public Solution(Spectrum spectrum){
      this.spectrum = spectrum;

    }

    /**
     * This method must be implemented by you. You may add other methods and subclasses as you see fit,
     * but they must remain within the Solution class. 
     * @return A Spectrum object that encapsulates the paths and other data generated by you
     */
    public Spectrum outputSpectrum(){
    		
    	return this.spectrum;
    }
}
